targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
      drift_dev:
        options:
          databases:
            app_database: lib/data/database/app_database.dart
          schema_dir: drift_schemas/
          store_date_time_values_as_text: true
          test_dir: test/data/database/migrations/
