name: shinga
description: "Shinga - Manga Tracker"
publish_to: "none"
version: 0.6.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  adaptive_dialog: ^2.4.2
  auto_route: ^10.1.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  crop_your_image: ^2.0.0
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  dotted_border: ^3.1.0
  fl_chart: ^1.0.0
  dio: ^5.8.0+1
  oauth2_client: ^4.2.0
  fpdart: ^1.1.1
  modal_bottom_sheet: ^3.0.0
  infinite_scroll_pagination: ^5.1.0
  stream_transform: ^2.1.1
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.7
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  flex_color_scheme: ^8.2.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_svg: ^2.2.0
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  hugeicons: ^0.0.11
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  octo_image: ^2.1.0
  path_provider: ^2.1.5
  readmore: ^3.0.0
  retrofit: ^4.6.0
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0
  slang: ^4.7.3
  slang_flutter: ^4.7.0
  talker: ^4.9.3
  talker_bloc_logger: ^4.9.3
  talker_dio_logger: ^4.9.3
  talker_flutter: ^4.9.3
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.2.3
  slang_build_runner: ^4.7.0
  build_runner: ^2.5.4
  retrofit_generator: ^9.7.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  hive_ce_generator: ^1.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
