name: shinga
description: "Shinga - Manga Tracker"
publish_to: "none"
version: 0.9.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  visibility_detector: ^0.4.0+2
  animated_flip_counter: ^0.3.4
  adaptive_dialog: ^2.5.0
  auto_route: ^10.1.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  crop_your_image: ^2.0.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  pinput: ^5.0.2
  dotted_border: ^3.1.0
  fl_chart: ^1.1.1
  dio: ^5.9.0
  oauth2_client: ^4.2.0
  fpdart: ^1.1.1
  modal_bottom_sheet: ^3.0.0
  infinite_scroll_pagination: ^5.1.1
  stream_transform: ^2.1.1
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.7
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  flex_color_scheme: ^8.3.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_svg: ^2.2.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  hive_ce: ^2.13.2
  hive_ce_flutter: ^2.3.2
  hugeicons: ^0.0.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  octo_image: ^2.1.0
  path_provider: ^2.1.5
  responsive_framework: ^1.5.1
  sidebarx: ^0.17.2
  readmore: ^3.0.0
  retrofit: ^4.7.2
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  talker: ^5.0.1
  talker_bloc_logger: ^5.0.1
  talker_dio_logger: ^5.0.1
  talker_flutter: ^5.0.1
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.2.4
  slang_build_runner: ^4.8.1
  build_runner: ^2.7.1
  retrofit_generator: ^10.0.5
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  hive_ce_generator: ^1.9.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

flutter_launcher_icons:
  image_path_android: "assets/icon/android_icon.png"
  android: true
  adaptive_icon_background: "assets/icon/android_icon_background.png"
  adaptive_icon_foreground: "assets/icon/android_icon_foreground.png"
  adaptive_icon_monochrome: "assets/icon/android_icon_monochrome.png"
  windows:
    generate: true
    image_path: "assets/icon/windows_icon.png"
    icon_size: 48
