name: shinga
description: "Shinga - Manga Tracker"
publish_to: "none"
version: 0.10.3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  adaptive_dialog: ^2.5.0
  animated_flip_counter: ^0.3.4
  auto_route: ^10.2.0
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  crop_your_image: ^2.0.0
  device_info_plus: ^12.2.0
  dio: ^5.9.0
  dotted_border: ^3.1.0
  equatable: ^2.0.7
  fl_chart: ^1.1.1
  flex_color_scheme: ^8.3.1
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_form_builder: ^10.2.0
  flutter_inappwebview: ^6.1.5
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_svg: ^2.2.1
  flutter_web_auth_2: ^5.0.0-alpha.7
  form_builder_validators: ^11.2.0
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  hugeicons: ^1.1.1
  image_picker: ^1.2.0
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  mockito: ^5.5.0
  modal_bottom_sheet: ^3.0.0
  oauth2_client: ^4.2.0
  octo_image: ^2.1.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pinput: ^5.0.2
  readmore: ^3.0.0
  responsive_framework: ^1.5.1
  retrofit: ^4.7.3
  shimmer: ^3.0.0
  sidebarx: ^0.17.2
  skeletonizer: ^2.1.0
  slang: ^4.9.2
  slang_flutter: ^4.9.0
  stream_transform: ^2.1.1
  talker: ^5.0.2
  talker_bloc_logger: ^5.0.2
  talker_dio_logger: ^5.0.2
  talker_flutter: ^5.0.2
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  visibility_detector: ^0.4.0+2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.2.5
  build_runner: ^2.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  hive_ce_generator: ^1.10.0
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.6
  slang_build_runner: ^4.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - shorebird.yaml

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

flutter_launcher_icons:
  image_path_android: "assets/icon/android_icon.png"
  android: true
  adaptive_icon_background: "assets/icon/android_icon_background.png"
  adaptive_icon_foreground: "assets/icon/android_icon_foreground.png"
  adaptive_icon_monochrome: "assets/icon/android_icon_monochrome.png"
  windows:
    generate: true
    image_path: "assets/icon/windows_icon.png"
    icon_size: 48
