name: shinga
description: "Shinga - Manga Tracker"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_animate: ^4.5.2
  loading_animation_widget: ^1.3.0
  modal_bottom_sheet: ^3.0.0
  readmore: ^3.0.0
  auto_size_text: ^3.0.0
  infinite_scroll_pagination: ^5.0.0
  auto_route: ^10.0.1
  firebase_core: ^3.13.0
  dio: ^5.8.0+1
  slang: ^4.7.1
  intl: ^0.19.0
  slang_flutter: ^4.7.0
  freezed: ^3.0.6
  either_dart: ^1.0.0
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  flex_color_scheme: ^8.2.0
  talker: ^4.7.6
  talker_flutter: ^4.7.2
  talker_dio_logger: ^4.7.2
  talker_bloc_logger: ^4.7.6
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  hive_ce: ^2.11.1
  hive_ce_flutter: ^2.3.0
  cached_network_image: ^3.4.1
  octo_image: ^2.1.0
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  hugeicons: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.0.1
  slang_build_runner: ^4.7.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  hive_ce_generator: ^1.9.1

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
