name: ui_kit
description: "Reusable UI components"
version: 0.1.0

environment:
  sdk: ">=3.11.0"
  flutter: ">=3.41.0"

resolution: workspace

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  flex_color_scheme: ^8.4.0

  flutter:
    sdk: flutter

  flutter_form_builder: ^10.3.0+2
  hugeicons: ^1.1.7
  intl: ^0.20.2
  octo_image: ^2.1.0
  pinput: ^6.0.2
  shimmer: ^3.0.0
  sidebarx: ^0.17.2

flutter:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700